trigger:
- develop

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6a345f8f-a2fe-4bbc-88f1-6e8f5531633a'
  imageRepository: 'saikumarbomminenidotnetdemo'
  containerRegistry: 'cortlandcontainer.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'cortlandcontainer61943123-auth'

# Agent VM image name
pool:
  name: 'sai'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'sai'
-  task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(tag)'
    steps:
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy 
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: 'sai'
    environment: 'stage'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: 'admin-saikumar'
              namespace: 'saikumar'
              secretType: 'dockerRegistry'
              secretName: '$(imagePullSecret)'
              dockerRegistryEndpoint: '$(dockerRegistryServiceConnection)'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Azure subscription 1(b3672f4b-0a7d-410e-956e-8111c247d206)'
    azureResourceGroup: 'admin'
    kubernetesCluster: 'admin'
    namespace: 'saikumar'
    command: 'upgrade'
    chartType: 'Name'
    chartName: 'heml.reo'
    chartVersion: '1.16.0'
    valueFile: 'values.yaml'
    resetValues: true
    force: true
           
