provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "aks_rg" {
  name     = "AzureResource3"
  location = "South Central US"
}

resource "azurerm_kubernetes_cluster" "aks_cluster" {
  name                = "cortlandcluster"
  location            = azurerm_resource_group.aks_rg.location
  resource_group_name = azurerm_resource_group.aks_rg.name
  dns_prefix          = "myaks"

  default_node_pool {
    name       = "default"
    node_count = 2
    vm_size    = "Standard_B2ms"
  }
  service_principal {
    client_id     = "4b0b823c-4051-4dd1-833f-81b3d5c5b1b2"
    client_secret = "Qxi8Q~7i5yiD-Oxph3c1_P49vBxqy4KaHTkmDazJ"
  }

  tags = {
    environment = "development"
  }
}

resource "azurerm_storage_account" "storage_account" {
  name                     = "myself"
  resource_group_name      = azurerm_resource_group.aks_rg.name
  location                 = azurerm_resource_group.aks_rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  tags = {
    environment = "development"
  }
}