# Deploy to Azure Kubernetes Service
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Azure subscription 1(b3672f4b-0a7d-410e-956e-8111c247d206)'
    azureResourceGroup: 'admin'
    kubernetesCluster: 'admin'
    namespace: 'saikumar'
    command: 'upgrade'
    chartType: 'Name'
    chartName: 'charts'
    chartVersion: '1.16.0'
    valueFile: 'values.yaml'
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6a345f8f-a2fe-4bbc-88f1-6e8f5531633a'
  imageRepository: 'saikumarbomminenidotnetdemo'
  containerRegistry: 'cortlandcontainer.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'cortlandcontainer61943123-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'SaikumarBomminenidotnetdemo-1907.saikumar'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

         - task: HelmDeploy@0
           inputs:
             connectionType: 'Azure Resource Manager'
             azureSubscription: 'Azure subscription 1(b3672f4b-0a7d-410e-956e-8111c247d206)'
             azureResourceGroup: 'admin'
             kubernetesCluster: 'admin'
             namespace: 'saikumar'
             command: 'upgrade'
             chartType: 'Name'
             chartName: 'heml.reo'
             chartVersion: '1.16.0'
             valueFile: 'values.yaml'
